[2022-08-16 08:27:14,382] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.cr5 manual__2022-08-15T11:17:41.613828+00:00 [queued]>
[2022-08-16 08:27:14,413] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.cr5 manual__2022-08-15T11:17:41.613828+00:00 [queued]>
[2022-08-16 08:27:14,414] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-16 08:27:14,415] {taskinstance.py:1377} INFO - Starting attempt 3 of 4
[2022-08-16 08:27:14,416] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-16 08:27:14,451] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cr5> on 2022-08-15 11:17:41.613828+00:00
[2022-08-16 08:27:14,465] {standard_task_runner.py:52} INFO - Started process 5440 to run task
[2022-08-16 08:27:14,473] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'craw', 'cr5', 'manual__2022-08-15T11:17:41.613828+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/newtest.py', '--cfg-path', '/tmp/tmpvkiugtpj', '--error-file', '/tmp/tmpaucs5nmg']
[2022-08-16 08:27:14,476] {standard_task_runner.py:80} INFO - Job 81: Subtask cr5
[2022-08-16 08:27:14,627] {task_command.py:371} INFO - Running <TaskInstance: craw.cr5 manual__2022-08-15T11:17:41.613828+00:00 [running]> on host 74c2759f33bd
[2022-08-16 08:27:14,737] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=craw
AIRFLOW_CTX_TASK_ID=cr5
AIRFLOW_CTX_EXECUTION_DATE=2022-08-15T11:17:41.613828+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-15T11:17:41.613828+00:00
[2022-08-16 08:27:14,752] {base.py:68} INFO - Using connection ID 'mysql' for task execution.
[2022-08-16 08:27:14,755] {logger.py:11} INFO - ====== WebDriver manager ======
[2022-08-16 08:27:14,878] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome 104.0.5112
[2022-08-16 08:27:15,431] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/104.0.5112/chromedriver] found in cache
[2022-08-16 08:27:19,531] {local_task_job.py:221} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-08-16 08:27:19,541] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 5440. PIDs of all processes in the group: [5529, 5571, 5582, 5583, 5595, 5597, 5665, 5734, 5664, 5440]
[2022-08-16 08:27:19,551] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 5440
[2022-08-16 08:27:19,561] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-08-16 08:27:19,583] {process_utils.py:75} INFO - Process psutil.Process(pid=5665, status='terminated', started='08:27:15') (5665) terminated with exit code None
[2022-08-16 08:27:19,586] {process_utils.py:75} INFO - Process psutil.Process(pid=5571, status='terminated', started='08:27:15') (5571) terminated with exit code None
[2022-08-16 08:27:19,587] {process_utils.py:75} INFO - Process psutil.Process(pid=5583, status='terminated', started='08:27:15') (5583) terminated with exit code None
[2022-08-16 08:27:19,593] {process_utils.py:75} INFO - Process psutil.Process(pid=5734, status='terminated', started='08:27:15') (5734) terminated with exit code None
[2022-08-16 08:27:19,594] {process_utils.py:75} INFO - Process psutil.Process(pid=5597, status='terminated', started='08:27:15') (5597) terminated with exit code None
[2022-08-16 08:27:19,595] {process_utils.py:75} INFO - Process psutil.Process(pid=5582, status='terminated', started='08:27:15') (5582) terminated with exit code None
[2022-08-16 08:27:19,595] {process_utils.py:75} INFO - Process psutil.Process(pid=5664, status='terminated', started='08:27:15') (5664) terminated with exit code None
[2022-08-16 08:27:19,632] {process_utils.py:75} INFO - Process psutil.Process(pid=5529, status='terminated', started='08:27:15') (5529) terminated with exit code None
[2022-08-16 08:27:19,645] {process_utils.py:75} INFO - Process psutil.Process(pid=5440, status='terminated', exitcode=0, started='08:27:14') (5440) terminated with exit code 0
[2022-08-16 08:27:19,647] {process_utils.py:75} INFO - Process psutil.Process(pid=5595, status='terminated', started='08:27:15') (5595) terminated with exit code None
