[2022-08-18 04:39:00,083] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.cr6 manual__2022-08-18T04:38:28.162136+00:00 [queued]>
[2022-08-18 04:39:00,657] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.cr6 manual__2022-08-18T04:38:28.162136+00:00 [queued]>
[2022-08-18 04:39:00,659] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 04:39:00,666] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-18 04:39:00,670] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 04:39:00,863] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cr6> on 2022-08-18 04:38:28.162136+00:00
[2022-08-18 04:39:00,926] {standard_task_runner.py:52} INFO - Started process 2126 to run task
[2022-08-18 04:39:00,961] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'craw', 'cr6', 'manual__2022-08-18T04:38:28.162136+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/newtest.py', '--cfg-path', '/tmp/tmp9y1x2avn', '--error-file', '/tmp/tmp6by69cno']
[2022-08-18 04:39:00,986] {standard_task_runner.py:80} INFO - Job 179: Subtask cr6
[2022-08-18 04:39:01,641] {task_command.py:371} INFO - Running <TaskInstance: craw.cr6 manual__2022-08-18T04:38:28.162136+00:00 [running]> on host d59619969b18
[2022-08-18 04:39:13,379] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=craw
AIRFLOW_CTX_TASK_ID=cr6
AIRFLOW_CTX_EXECUTION_DATE=2022-08-18T04:38:28.162136+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-18T04:38:28.162136+00:00
[2022-08-18 04:39:13,506] {base.py:68} INFO - Using connection ID 'mysql' for task execution.
[2022-08-18 04:39:13,531] {logger.py:11} INFO - ====== WebDriver manager ======
[2022-08-18 04:39:14,104] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome 104.0.5112
[2022-08-18 04:39:14,848] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/104.0.5112/chromedriver] found in cache
