[2022-08-18 13:36:54,529] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.db manual__2022-08-18T13:12:23.100461+00:00 [queued]>
[2022-08-18 13:36:54,545] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.db manual__2022-08-18T13:12:23.100461+00:00 [queued]>
[2022-08-18 13:36:54,545] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 13:36:54,545] {taskinstance.py:1377} INFO - Starting attempt 5 of 6
[2022-08-18 13:36:54,546] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 13:36:54,567] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): db> on 2022-08-18 13:12:23.100461+00:00
[2022-08-18 13:36:54,572] {standard_task_runner.py:52} INFO - Started process 84 to run task
[2022-08-18 13:36:54,576] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'craw', 'db', 'manual__2022-08-18T13:12:23.100461+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/newtest.py', '--cfg-path', '/tmp/tmpweajowtb', '--error-file', '/tmp/tmpe345y25j']
[2022-08-18 13:36:54,577] {standard_task_runner.py:80} INFO - Job 170: Subtask db
[2022-08-18 13:36:54,681] {task_command.py:371} INFO - Running <TaskInstance: craw.db manual__2022-08-18T13:12:23.100461+00:00 [running]> on host 33e30e13fab9
[2022-08-18 13:36:54,853] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=craw
AIRFLOW_CTX_TASK_ID=db
AIRFLOW_CTX_EXECUTION_DATE=2022-08-18T13:12:23.100461+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-18T13:12:23.100461+00:00
[2022-08-18 13:36:54,886] {base.py:68} INFO - Using connection ID 'mysql' for task execution.
[2022-08-18 13:37:04,890] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/connections.py", line 614, in connect
    (self.host, self.port), self.connect_timeout, **kwargs
  File "/usr/local/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/newtest.py", line 116, in totaldb
    conn= mysql_hook.get_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py", line 166, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/connections.py", line 664, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'mysql' ([Errno -3] Temporary failure in name resolution)")
[2022-08-18 13:37:04,935] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=craw, task_id=db, execution_date=20220818T131223, start_date=20220818T133654, end_date=20220818T133704
[2022-08-18 13:37:05,553] {standard_task_runner.py:97} ERROR - Failed to execute job 170 for task db ((2003, "Can't connect to MySQL server on 'mysql' ([Errno -3] Temporary failure in name resolution)"); 84)
[2022-08-18 13:37:05,598] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-18 13:37:05,732] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
