[2022-08-15 11:56:10,521] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.cr6 manual__2022-08-15T11:56:08.347793+00:00 [queued]>
[2022-08-15 11:56:10,533] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.cr6 manual__2022-08-15T11:56:08.347793+00:00 [queued]>
[2022-08-15 11:56:10,534] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-15 11:56:10,534] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-15 11:56:10,535] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-15 11:56:10,553] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cr6> on 2022-08-15 11:56:08.347793+00:00
[2022-08-15 11:56:10,558] {standard_task_runner.py:52} INFO - Started process 5612 to run task
[2022-08-15 11:56:10,562] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'craw', 'cr6', 'manual__2022-08-15T11:56:08.347793+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/newtest.py', '--cfg-path', '/tmp/tmp69gqo850', '--error-file', '/tmp/tmp7pnz954j']
[2022-08-15 11:56:10,564] {standard_task_runner.py:80} INFO - Job 16: Subtask cr6
[2022-08-15 11:56:10,641] {task_command.py:371} INFO - Running <TaskInstance: craw.cr6 manual__2022-08-15T11:56:08.347793+00:00 [running]> on host 340b8712908c
[2022-08-15 11:56:10,747] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=craw
AIRFLOW_CTX_TASK_ID=cr6
AIRFLOW_CTX_EXECUTION_DATE=2022-08-15T11:56:08.347793+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-15T11:56:08.347793+00:00
[2022-08-15 11:56:10,762] {base.py:68} INFO - Using connection ID 'mysql' for task execution.
[2022-08-15 11:56:10,767] {logger.py:11} INFO - ====== WebDriver manager ======
[2022-08-15 11:56:10,913] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome 104.0.5112
[2022-08-15 11:56:11,505] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/104.0.5112/chromedriver] found in cache
[2022-08-15 11:58:40,449] {logging_mixin.py:115} INFO - https://shopping-phinf.pstatic.net/main_1531030/15310309538.20200403164240.jpg?type=f140 비프렌드 G키보드2 프리미엄 레인보우 21,900원 배송도 빨리되고 눌렀을때 소리도 듣기 불편한거없이 좋았습니다가격도 저렴한데 포장도 완벽하고 자판 누를때 정말 부드러워요!!고자없이 디자인 색감 너무 이쁘게 아직도 잘 사용중이에요 ㅎㅎ부드럽고 조용한 키감
기계식 쓰다 바꿨는데 전 이게 훨씬 좋네요기본적으로 타격감 괜찮고 가격대비 효율 정말 좋은거 같습니다.일단 이쁘구요!! 타자칠때 소리가 작은건 아니지만 저는 그 타다닥 소리 좋아해서 잘 쓰고있습니다!전 이 키보드만 4개째 구매 중입니다.
적당한 무게감에,
좋은 타격감,
결정적으로 사무실에서 쓰기에도 적당한 조용한 소음
튼튼하기까지 합니다.
강력 추천합니다.이쁘고 소리도 둔하니 좋고 디자인도 깔끔하고 대만족입니다 ^-^잘사용하고 있어요
이가격대에 괜찮은 제품사서 대만족중입니다키보드 불 은은하게 들어오고 타격감도 좋네요 가성비 좋습니다라이트를 켜도 이쁘고 꺼도 이쁘네요 ! 타자 칠때도 좋고 소리도 크지도 않고 좋습니다 ! 잘쓸게요 ~~타감도 좋고 블랙색상이라 디자인 걱정을 좀 했는데
생각보다 깔끔한 디자인에 어디에도 어울릴 것 같아요
가성비도 좋고 만족합니다키보드 누를때 소리가 크긴하지만 아들이 엄청 맘에들어합니다이런 키보드(?)는 처음 써보는데 키감도 좋고 잘 쓸 것 같아요!색상도 고급져보이고 별 기대없이 구매했는데 맘에듭니다..^^원래 쓰던거 다시산거라서 좋습니다. 색감이 화려해졌네요ㅎ키보드가 예뻐서 일에 집중이 안됩니다. 책임지세요ㅠㅠ💛아이들 키보드 교체해줬는데 좋아하네요
배송 제품 모두만족첨엔 타격감에 조금 불편해하더니, 지금은 아주 좋아합니다.넘좋아요 게임키보드로 탁월 부드럽게잘쳐짐 굿 두개샀어요가성비용으로 많이 추천하고 있습니다.타자감 너무 좋고 가성비 최고 입니다!!키보드 가성비 굿 피파하는데 아주만족가격대비 가성비 최고인것 같습니다~~!!배송 빠르고
제품 가성비 너무좋습니다쓰던게 고장나서 새로 샀어요 괜찮네요각격대비 소음도 없고 성능 만족합니다타자 느낌이 좋아요 소리도 적당하고요저렴하고 상품이 정말 가격대비 좋아영진짜 좋네요 배송도빠르고 번창하세요좋으네요 가격싸고 품질 너무 좋습니다최고 소리작고 ㅎ 포장꼼꼼 배송빨라요키보드칠때 톡톡 소리나면서 잘 쳐져요As도 바로 해서 보내주시고 감사합니다아들이 아주좋아합니다 가성비 좋네요배송빠르고 좋아요. 두번째구입이네요안전포장되어 빠르게 배송되었습니다.며칠간 사용해보니 매우 만족스려워요색상도 이쁘고 터치감이 정말 좋아요!!집에서 타다닥 편한하게 사용중입니다쓰던거라 소리도 적고 좋아요타이핑 감도좋고, 은은하게 퍼지는 키보드 조명 맘에듭니다. 만족합니다.가격대비 상당히 만족합니다편하고 터치감 좋아요. 추천~키보드가 너무 마음에들어용타자감이좋고 디자인도 이쁨너무좋아요 터치감두 좋네요편리하고 좋아요 추천드려요치는느낌 디자인 완전조아요괜찮은거같아요 맘에들어요.정말 예쁘네요~추천합니다~^^가성비 극강입니다 꼭사세여심플하면서도 괜찮은거같음.배송 빠르고 사용하기좋아요정말 좋아욘 가격대비 정말 잘산거 같음 특히 투닥티닥 서리가
맘에 드네욘고장없이 잘사용하고있어요색상이예쁘네요.소리도작고색상 촉감 다마음에들어요!~So cute and works well even with Mac~좋습니당피시방 온거갿네유
[2022-08-15 11:58:40,451] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/newtest.py", line 97, in crawling
    cursor.execute("INSERT INTO info VALUES (%s, %s, %s, %s);",(image,name,price,review))
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1366, "Incorrect string value: '\\xF0\\x9F\\x92\\x9B\\xEC\\x95...' for column 'review' at row 1")
[2022-08-15 11:58:40,465] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=craw, task_id=cr6, execution_date=20220815T115608, start_date=20220815T115610, end_date=20220815T115840
[2022-08-15 11:58:40,481] {standard_task_runner.py:97} ERROR - Failed to execute job 16 for task cr6 ((1366, "Incorrect string value: '\\xF0\\x9F\\x92\\x9B\\xEC\\x95...' for column 'review' at row 1"); 5612)
[2022-08-15 11:58:40,512] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-15 11:58:40,538] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
